export type OperationBulletinSummaryReportType = {
  FACTORYID: number;
  SECTIONID: number;
  STYLEID: number;
  NAME: string;
  TARGERPERHOUR: number;
  EFFICIENCY: number;
  SMVM: number;
  SMVH: number;
  SMVI: number;
  OP: number;
  HLP: number;
  IR: number;
  PLANWS: number;
  TOTALALLOTTEDMP: number;
  TOTALSMV: number;
  GSM: number;
  SAMPLE_TYPE: string;
  MAIN_FABRIC: string;
  STYLENO: string;
  ITEMTYPE: string;
  BUYER_NAME: string;
  LAYOUT_DATE: string;
  SAMPLE_DATE: string;
};
